### ISSUE TITLE
Add local storage

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#10]
## Value statement
As a **minigolf player** 
I need **to save relevant game details** 
so that **I can view them at any time** 

## Description 

/

## Acceptance criteria
- [x] Click on "Save"-button saves form data locally
- [x] While filling in the form, the input values are also saved locally

## Tasks
- [x] Create feature branch
- [x] Add local storage logic to SaveGameForm and GameCard component
- [x] Write components tests

## Size
small
