### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#11]
## Value statement
As a **minigolf player** 
I need **to save game details correctly and in the same way** 
so that **I can compare them** 

## Description 

/

## Acceptance criteria
- [x] Inputs are valid, if ...
- [x] ... they are not empty
- [x] ... if they consist of not only whitespace
- [x] Total shots winner(s) input only accepts numbers between 18 - 126
- [x] All inputs trim useless spaces
- [x] Error message ...
- [x] ... appears when submitting the form, if any input is invalid
- [x] ... describes the respective input error

## Tasks
- [x] Create feature branch
- [x] Add validation logic to SaveGameForm component
- [x] Write components tests

## Size
small
