### ISSUE TITLE
Implement scorecard

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#17]
## Value statement
As a **minigolf player** 
I need **to save scorecards** 
so that **I know exactly the number of shots per player per hole** 

## Description 

![#7_Implement-Scorecard](https://user-images.githubusercontent.com/71652521/103679796-9a208800-4f85-11eb-98b2-40bc6f70bb9b.png)

![UserStory_implement-scorecard](https://user-images.githubusercontent.com/71652521/103778412-80894a00-5032-11eb-9d35-66383be53a05.png)

## Acceptance criteria

**FormScores:**
- [x] Represents a scorecard
- [x] Consists of 18 inputs for each player 
- [x] Has a "Cancel"- and "Save"-button
- [x] All inputs only accept numbers between 1 and 7
- [x] "Save"-button is disabled until all inputs are valid

**CreatePage:**
- [x] First render shows FormKeyInfos component
- [x] Click on "Save"-button in FormKeyInfos component ...
- [x] ... saves input values
- [x] ... shows FormScores instead of FormKeyInfos
- [x] Click on "Save"-button in FormScores component ...
- [x] ... saves complete new game
- [x] ... redirects to OverviewPage
- [x] Click on "Cancel"-button in either FormKeyInfos or FormScores component ...
- [x] ... aborts the save process
- [x] ... redirects to OverviewPage

**GameCard:**
- [x] Has an additional "Details"-button
- [x] Click on "Details"-button redirects to new DetailsPage

**DetailsPage:**
- [x] Shows all saved game details including the new scorecard details
- [x] Has a "Back"-button
- [x] Click on "Back"-button redirects to OverviewPage

**EditPage:**
- [x] Inputs are filled with game details of the respective game
- [x] First render shows FormKeyInfos component
- [x] Click on "Save"-button in FormKeyInfos component ...
- [x] ... saves changes
- [x] ... shows FormScores instead of FormKeyInfos
- [x] Click on "Save"-button in FormScores component ...
- [x] ... saves changes and updates respective game profile
- [x] ... redirects to OverviewPage
- [x] Click on "Cancel"-button in either FormKeyInfos or FormScores component ...
- [x] ... aborts the edit process
- [x] ... redirects to OverviewPage

## Tasks
- [x] Create feature branch
- [x] Update Form component to FormKeyInfos component
- [x] Create FormScores component in Styleguidist
- [x] Write component tests
- [x] Expand CreatePage component
- [x] Write component tests
- [x] Expand GameCard component
- [x] Write component tests
- [x] Create DetailsPage component in Styleguidist
- [x] Write component tests
- [x] Expand EditPage component
- [x] Write component tests
- [x] Update and add components in/to App (feature implementation with state)
- [x] Update router
- [x] Implement design

## Size
large
