### ISSUE TITLE
Add Router

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#18]
## Value statement
As a **minigolf player** 
I need **to navigate between different pages** 
so that **I have a better overview of different app functionalities** 

## Description 

![#6_Add-Router](https://user-images.githubusercontent.com/71652521/102808176-39f3e880-43c0-11eb-8bd5-97987849ff26.png)

![UserStory_add-router](https://user-images.githubusercontent.com/71652521/102807851-b76b2900-43bf-11eb-89f0-5c10c2e17ff3.png)

## Acceptance criteria
- [x] The app ...
- [x] ... has two pages - "Home" and "Create"
- [x] ... has a navigation bar (placed in the footer) with a home and a plus icon
- [x] ... has the same header and footer on every page
- [x] The "Home" page shows all saved gamecards (scrollable)
- [x] The "Create" page shows the form (normal modus and edit modus)
- [x] The home navigation icon redirects to the "Home" page
- [x] The plus navigation icon redirects to the "Create" page
- [x] Click on "Save"-button at the "Create" page ...
- [x] ... executes all previous functions
- [x] ... redirects to "Home" page
- [x] Click on "Edit"-button of a gamecard redirects to "Create" page in edit modus
- [x] Click on "Save"- and "Cancel"-button at the "Create" page in edit modus ...
- [x] ... executes all previous functions
- [x] ... redirects to "Home" page

## Tasks
- [x] Create feature branch
- [x] Create Header component in Styleguidist
- [x] Create Footer component in Styleguidist
- [x] Create Navigation component in Styleguidist
- [x] Write components tests
- [x] Add components to App
- [x] Implement router logic in App 
- [x] Implement design

## Size
medium
