### ISSUE TITLE
Create gamecards list - large

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#2]
## Value statement
As a **minigolf player** 
I need **a place to note and save relevant game details** 
so that **I can track and analyze my play as well as the play of others in order to improve** 

## Description 

![User-Story-1 1](https://user-images.githubusercontent.com/71652521/99180754-564d9700-2729-11eb-94fa-f6d43a5fa048.png)

## Acceptance criteria
**SaveGameForm**
- [ ] The user fills out the form data and submits the form by clicking the button "Save Game"
- [ ] **Date input**: Only accepts one date format
- [ ] **Players input**: Typing name and pressing enter afterwards results in a tag with the name in the "winner" section. Afterwards the focus is back on the players input field, so that the user can directly continue with the next name. Name tags have an "x" and can be deleted by cklicking on the "x". First and last name are valid inputs, also abbreviations with ".". Special characters are not valid but numbers are. Spaces should be trimmed, except one space between first and last name, if existing.
- [ ] **Winner input**: Shows all name tags created from the players input. Name tags are radio buttons. By clicking one name radio button the user identifies the winner of the respective game. The clicked name tag changes its color. More than one winner is possible.
- [ ] **"Save Game"-Button**: Submits the form and resets it as well. Focus is back on the first input. 
- [ ] Input values are saved locally during completion
- [ ] The form doesn't scroll

**GameCard**
- [ ] Shows the entered game data in a respective gamecard
- [ ] All elements are always visible
- [ ] The list of all saved gamecards starts with the newest on the top
- [ ] Gamecards are saved locally
- [ ] During scrolling only the list scrolls - not the form on the top. The list doesn't scroll behind the form.

## Tasks
- [ ] Create feature branch
- [ ] Create SaveGameForm component in Storybook
- [ ] Write component tests
- [ ] Add component to app (feature implementation with state and local storage)
- [ ] Add missing styles
- [ ] Create GameCard component in Storybook
- [ ] Write component tests
- [ ] Add component to app (feature implementation with state and local storage)
- [ ] Add missing styles

## Size
large
