### ISSUE TITLE
Game overview table

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#3]
## Value statement
As a **minigolf player** 
I need **a place to note and save relevant game details** 
so that **I can track and analyze my play as well as the play of others in order to improve** 

## Description 

![User-Story-B-1](https://user-images.githubusercontent.com/71652521/99181634-fdcdc800-272f-11eb-9fa4-de3b6889f397.png)

## Acceptance criteria
- [ ] The user fills out the the table with relevant game information.
- [ ] By clicking the "Save"-Button, all data is saved locally and the focus goes back to the new input line. 

## Tasks
- [ ] Create feature branch
- [ ] Create GameOverview component in Storybook
- [ ] Create "Save"-Button component in Storybook
- [ ] Write component tests
- [ ] Add components to app (feature implementation with state and local storage)
- [ ] Add missing styles

## Size
small
