### ISSUE TITLE
Adding table rows

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#4]
## Value statement
As a **minigolf player** 
I need **the opportunity to add new table rows** 
so that **I can unlimitedly save all my games and not just a few** 

## Description 

![User-Story-B-2](https://user-images.githubusercontent.com/71652521/99183874-6ec8ac00-273f-11eb-8011-db582794e6ac.png)

## Acceptance criteria
- [ ] By clicking the "Plus"-Button a new, empty and fillable table row appears at the end of the table.

## Tasks
- [ ] Create feature branch
- [ ] Create AddButton component in Storybook
- [ ] Write component tests
- [ ] Add component to app and GameOverview table (feature implementation with state)
- [ ] Write additional component test for GameOverview component
- [ ] Add missing styles

## Size
small
