### ISSUE TITLE
Delete table rows

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#5]
## Value statement
As a **minigolf player** 
I need **the opportunity to delete existing table rows and game entries** 
so that **I can remove games from the list, in the case I do not need them to be on the list anymore or when I accidently typed in wrong data** 

## Description 

![User-Story-B-3](https://user-images.githubusercontent.com/71652521/99184038-99ffcb00-2740-11eb-9df3-042e4fde8672.png)

## Acceptance criteria
- [ ] At the end of each row (filled with data or empty) sits a "Minus"-Button
- [ ] By clicking the "Minus"-Button the respective table row, including all data, is deleted

## Tasks
- [ ] Create feature branch
- [ ] Create DeleteButton component in Storybook
- [ ] Write component tests
- [ ] Add component to app and GameOverview table (feature implementation with state)
- [ ] Write additional component test for GameOverview component
- [ ] Add missing styles

## Size
small
