### ISSUE TITLE
Edit table rows

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#6]
## Value statement
As a **minigolf player** 
I need **the opportunity to edit the game entries** 
so that **I don't have to remove the entry and create a whole new one** 

## Description 

![User-Story-B-4](https://user-images.githubusercontent.com/71652521/99184608-7048a300-2744-11eb-8f53-c535c5d4f3ec.png)

## Acceptance criteria
- [ ] At the end of each filled and saved row sits an "Edit"-Button
- [ ] By clicking the "Edit"-Button the respective table row is editable again and can be saved after applying changes
- [ ] When the "Edit"-Button is clicked and the table row is editable, the "Edit"-Button disappears

## Tasks
- [ ] Create feature branch
- [ ] Create EditButton component in Storybook
- [ ] Write component tests
- [ ] Add component to app and GameOverview table (feature implementation with state)
- [ ] Write additional component test for GameOverview component
- [ ] Add missing styles

## Size
small
