### ISSUE TITLE
Create gamecards list

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#7]
## Value statement
As a **minigolf player** 
I need **a place to note relevant game details** 
so that **I can track and analyze my play as well as the play of others in order to improve** 

## Description 

![User-Story-D-1](https://user-images.githubusercontent.com/71652521/99254092-1ca48b00-2812-11eb-85f9-7b3a4d2ac4c9.png)

## Acceptance criteria
**Form**
- [x] Click on "Save"-button ...
- [x] ... submits form
- [x] ... resets form
- [x] ... sets focus back to the first input
- [x] Date input field is of type date and has the browsers presets date format
- [x] Validation is not part of this user story
- [x] No error message appears, in case the input fields are filled in wrong

**Gamecard**
- [x] The list of all saved gamecards starts with the newest on top

**General**
- [x] Whole body is scrollable

## Tasks
- [x] Create feature branch
- [x] Create SaveGameForm component in Styleguidist
- [x] Write component tests
- [x] Add component to App (feature implementation with state)
- [x] Add missing styles
- [x] Create GameCard component in Styleguidist
- [x] Write component tests
- [x] Add component to App (feature implementation with state)
- [x] Add missing styles

## Size
medium
