### ISSUE TITLE
Delete gamecard

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#8]
## Value statement
As a **minigolf player** 
I need **to delete existing gamecards** 
so that **I can remove games from the list, if they are irrelevant**

## Description 

![#4_Delete-Gamecard](https://user-images.githubusercontent.com/71652521/99293198-994f5d80-2842-11eb-96b7-d466e1a51cb8.png)

## Acceptance criteria
- [x] Each gamecard has an "Delete"-button
- [x] By clicking the "Delete"-button ...
- [x] ... the gamecard disappears
- [x] ... the user is asked, whether to delete the gamecard or not
- [x] By clicking the "Delete"-button again the gamecard is deleted permanently

## Tasks
- [x] Create feature branch
- [x] Create DeleteButton component in Styleguidist
- [x] Write component tests
- [x] Add component to GameCard (feature implementation with state)
- [x] Write additional component test for GameCard component
- [x] Create DeleteConfirmation component
- [x] Write component tests
- [x] Add component to App (feature implementation with state)
- [x] Add missing styles

## Size
medium
