### ISSUE TITLE
Edit gamecard

### ISSUE THREAD

**Issue by JanaHaeusler** [JanaHaeusler/capstone-project#9]
## Value statement
As a **minigolf player** 
I need **the opportunity to edit the game cards** 
so that **I don't have to delete a game card and create a new one, in order to update game data** 

## Description 

![#5_Edit-GameCard](https://user-images.githubusercontent.com/71652521/102798619-a74c4d00-43b1-11eb-8117-ebe5e9b1e631.png)

## Acceptance criteria
- [x] Each gamecard has an "Edit"-button
- [x] By clicking the "Edit"-button the input form appears as overlay
- [x] All input values are preset and contain the saved game data
- [x] By clicking the "Save"-button ...
- [x] ... the input form overlay disappears
- [x] ... the game card data is updated 
- [x] By clicking the "Cancel"-button ...
- [x] ... the input form overlay disappears
- [x] ... the game card data does not change
- [x] ... entered changes are not saved

## Tasks
- [x] Create feature branch
- [x] Create EditButton component in Styleguidist
- [x] Write component tests
- [x] Create CancelButton in Styleguidist
- [x] Write component tests
- [x] Create EditGameForm in Styleguidist
- [x] Write component tests
- [x] Add SaveButton and CancelButton components to EditGameForm component (feature implementation with state)
- [x] Add EditButton to GameCard component (feature implementation with state)
- [x] Write additional component test for GameCard component
- [x] Write additional component test for EditGameForm component
- [x] Add missing styles

## Size
medium
